### ISSUE TITLE
Incomplete attributes for some resources.

### ISSUE THREAD

**Issue by bjorg** [jakejscott/Humidifier#11]
I'd like to use the nested `Attributes` class to generate valid `Fn::GetAtt` expressions. While randomly poking around the Humidifier resource definitions, I noticed that some attribute definitions are  incomplete.

For example, [`Humidifier.AmazonMQ.Broker`](https://github.com/jakejscott/Humidifier/blob/master/src/Humidifier/AmazonMQ/Broker.cs) is missing `Arn`, `ConfigurationId`, `ConfigurationRevision`. Also, `BrokerId` doesn't actually exist. See [`AWS::AmazonMQ::Broker`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-broker.html) documentation page.

Similarly, [`Humidifier.ElastiCache.CacheCluster`](https://github.com/jakejscott/Humidifier/blob/master/src/Humidifier/ElastiCache/CacheCluster.cs) is missing `ConfigurationEndpoint.Address`, `ConfigurationEndpoint.Port`, `RedisEndpoint.Address`, and `RedisEndpoint.Port`. See [`AWS::ElastiCache::CacheCluster`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html#aws-properties-elasticache-cache-cluster-ref) documentation page.

Most of the ones I checked were complete and accurate, so this is not a widespread issue. I did not check all of them, so I don't know if there are additional ones.

Let me know if I can provide additional information. Thanks.

**Comment by jakejscott** [comment]
I just re-ran the code generator and checked the AWS::ElasticCache::CacheCluster and yeah it's missing those attributes. 

I'm downloading the spec for US East (N. Virginia)
https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

**Comment by jakejscott** [comment]
Unfortunately the spec sometimes lags behind, or is incorrect. The only thing I can do is periodically re-run the code generator and hope that someone at AWS has updated those resource spec files. They do often update them. 

They also document whenever there was a release to cloudformation service here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

So usually it's a good idea to run it whenever they do a release (or a few days after). It's also a cool way to find out when new services become available :)

**Comment by bjorg** [comment]
I had a suspicion it might be an upstream issue. Thanks for checking.

The CloudFormation release notes are on my regular reading list as I'm working heavily with CloudFormation. Humidifier has been a huge help. Thanks for creating it!

**Comment by bjorg** [comment]
Well, I forwarded an example of the inconsistency to my AWS rep so they are at least aware of it. The `AWS::AmazonMQ::Broker` spec if still broken, but the `AWS::ElastiCache::CacheCluster` seems correct.

They are obviously no relying on the JSON spec to generate their docs!

**Comment by jakejscott** [comment]
There's a whole lot of new goodies released https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

Hopefully they update the spec soon so that I can try out Lambda Layers!

**Comment by jakejscott** [comment]
Yeah I'm having a play around with custom runtimes now (following this tutorial https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html) 

Also looks like some nice new identity stuff coming...
https://www.youtube.com/watch?v=FteCJQcTDc4
'
