### ISSUE TITLE
VPCEndpoint object has an incorrectly capitalized property

### ISSUE THREAD

**Issue by richarddowner** [jakejscott/Humidifier#12]
Hey Jake,

Seems in the latest version of Humidifier.Json the VPCEndpoint object takes a VPCEndpointType property.
However the Cloudformation requires VpcEndpointType. 

Getting an error: "Encountered unsupported property VPCEndpointType"
And docs show property of: "VpcEndpointType" : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html

Cheers

**Comment by richarddowner** [comment]
Looks like it might be a bug in the: https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

**Comment by bjorg** [comment]
I submitted a JSON spec issue to my AWS rep on Dec. 1st, but nothing happened. If you find a better channel for getting these fixed, please share! Otherwise, we may need a "fix up" sheet that can be run post-import.

**Comment by jakejscott** [comment]
https://github.com/jakejscott/Humidifier/commit/dce139b9088e49976b6cec755039c8cfffa23c06
